version: '3.4'
services:
  edf-demo-dev-alfresco-share:
    image: alfresco-share-edf-demo-dev-alfresco:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../edf-demo-dev-alfresco-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: edf-demo-dev-alfresco-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  edf-demo-dev-alfresco-acs:
    image: alfresco-content-services-edf-demo-dev-alfresco:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../edf-demo-dev-alfresco-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - edf-demo-dev-alfresco-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - edf-demo-dev-alfresco-postgres
  edf-demo-dev-alfresco-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - edf-demo-dev-alfresco-db-volume:/var/lib/postgresql/data
  edf-demo-dev-alfresco-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: edf-demo-dev-alfresco-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: edf-demo-dev-alfresco-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - edf-demo-dev-alfresco-ass-volume:/opt/alfresco-search-services/contentstore
      - edf-demo-dev-alfresco-ass-volume:/opt/alfresco-search-services/data
volumes:
  edf-demo-dev-alfresco-acs-volume:
    external: true
  edf-demo-dev-alfresco-db-volume:
    external: true
  edf-demo-dev-alfresco-ass-volume:
    external: true